In [1]:
import time
i=time.time()

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import seaborn as sns
md_c=None
md_r=1

from sklearn.ensemble import RandomForestClassifier as RFC
RFC=RFC(max_depth=md_c)
from sklearn.ensemble import RandomForestRegressor as RFR
RFR=RFR(max_depth=md_r)
from sklearn import metrics

In [2]:
imp_fert=pd.read_csv('~/git/BD/temp/imp_fert_quanti.csv')
imp_fert.shape

(39719, 7)

# Filtra UF e produtos de interesse específico

In [3]:
imp_fert=imp_fert[(imp_fert.SG_UF_NCM=='BA')].drop(columns='SG_UF_NCM')
imp_fert=imp_fert[~imp_fert.nick.isin(['NP_k','NPK_k'])]


imp_fert.shape

(1820, 6)

# Salva as reais datas de início e fim dos registros

In [4]:
imp_fert.insert(0,'date',pd.to_datetime(imp_fert.CO_ANO.astype(str)+'/'+imp_fert.CO_MES.astype(str)+'/1'))

date_min=imp_fert.date.min()
date_max=imp_fert.date.max()

In [5]:
imp_fert.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1820 entries, 36 to 39681
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1820 non-null   datetime64[ns]
 1   CO_ANO      1820 non-null   int64
 2   CO_MES      1820 non-null   int64
 3   nick        1820 non-null   object
 4   CO_PAIS     1820 non-null   int64
 5   CO_URF      1820 non-null   int64
 6   KG_LIQUIDO  1820 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 113.8+ KB

In [6]:
filtro=imp_fert[imp_fert.CO_ANO>imp_fert.CO_ANO.max()-6][['nick','CO_PAIS','CO_URF']].astype(str).drop_duplicates()

cols_to_sparse=['CO_ANO','CO_MES','nick','CO_PAIS','CO_URF']

imp_fert[cols_to_sparse]=imp_fert[cols_to_sparse].astype('category')

imp_fert=imp_fert.groupby(by=['CO_ANO','CO_MES','nick','CO_PAIS','CO_URF'], observed=False).KG_LIQUIDO.sum()\
.reset_index()
imp_fert.shape

(483840, 6)

In [7]:
imp_fert[['nick','CO_PAIS','CO_URF']]=imp_fert[['nick','CO_PAIS','CO_URF']].astype(str)
imp_fert.shape

(483840, 6)

In [8]:
imp_fert=imp_fert.merge(filtro)

imp_fert.shape

(14784, 6)

# Corrige bordas da matriz esparsa

In [9]:
imp_fert['date']=pd.to_datetime(imp_fert.CO_ANO.astype(str)+'/'+imp_fert.CO_MES.astype(str)+'/1')

imp_fert=imp_fert[(imp_fert.date>=date_min)&(imp_fert.date<=date_max)]

imp_fert.shape

(14344, 7)

# Diferencia ocorrências reais de não ocorrência*
*registradas com quantidades iguais a zero.

In [10]:
imp_fert=imp_fert.assign(oc=0)

imp_fert.loc[imp_fert.KG_LIQUIDO>0,'oc']=1

In [11]:
imp_fert

      CO_ANO CO_MES     nick CO_PAIS  CO_URF  KG_LIQUIDO       date  oc
88      1997      3    MAP_k     160  317900         0.0 1997-03-01   0
89      1997      3    MAP_k     160  417900         0.0 1997-03-01   0
90      1997      3    MAP_k     160  517800         0.0 1997-03-01   0
91      1997      3    MAP_k     160  717600         0.0 1997-03-01   0
92      1997      3    MAP_k     160  717800         0.0 1997-03-01   0
...      ...    ...      ...     ...     ...         ...        ...  ..
14427   2024      4  UREIA_k     676  517800   7003175.0 2024-04-01   1
14428   2024      4  UREIA_k     676  817800         0.0 2024-04-01   0
14429   2024      4  UREIA_k     676  917800         0.0 2024-04-01   0
14430   2024      4  UREIA_k     676  927700         0.0 2024-04-01   0
14431   2024      4  UREIA_k     999  517800   7868599.0 2024-04-01   1

[14344 rows x 8 columns]

# Procede os teste

In [12]:
# Cria df para coletar os resultados do loop
q=pd.DataFrame()
r=pd.DataFrame()

# Inicia loop sobre as datas
for date in imp_fert.date.unique():
    
    # Abre contagem de tempo para o loop externo
    i_p=time.time()
    
    # Filtra deixando passar registros menores ou iguais a data do loop
    imp_fert_t=imp_fert[(imp_fert.date<=date)]

    # Se restarem 10 anos de registro:
    if (imp_fert_t.date.max()-imp_fert_t.date.min()).days/365>=10:

        # Adequa formato da data para processamento ML
        imp_fert_t['date']=imp_fert_t.date.astype(int)

        # CLASSIFCAÇÃO

        cols=['CO_MES','nick','CO_PAIS','CO_URF']
        imp_fert_t[cols]=imp_fert_t[cols].astype('category')
        

        # Transforma categoricos em dummies
        imp_fert_dumm=pd.get_dummies(imp_fert_t,prefix_sep='~')
        
        # Identifica registros para treino e teste
        train_dumm=imp_fert_dumm[imp_fert_dumm.date< imp_fert_dumm.date.max()]
        test_dumm =imp_fert_dumm[imp_fert_dumm.date==imp_fert_dumm.date.max()]
        

        # Identifica X e y classifier
        X_train_c=train_dumm.drop(columns=['KG_LIQUIDO','oc'])
        y_train_c=train_dumm.oc
        
        X_test_c =test_dumm.drop(columns=['KG_LIQUIDO','oc'])
        y_test_c =test_dumm.oc
        
        
        # Fit classifier
        RFC.fit(X_train_c,y_train_c)
        # Predict classifier
        test_pred_c=X_test_c.assign(oc_pred=RFC.predict(X_test_c)).assign(oc=y_test_c)

        q=pd.concat([q,test_pred_c])

        
        
        # REGRESSÃO

        imp_fert_t=imp_fert_t[imp_fert_t.oc==1]

        if len(imp_fert_t[imp_fert_t.date.astype('datetime64[ns]')==date])>0:
    
            # Transforma categoricos em dummies
            imp_fert_dumm=pd.get_dummies(imp_fert_t,prefix_sep='~')
            
            # Identifica registros para treino e teste
            train_dumm=imp_fert_dumm[imp_fert_dumm.date< imp_fert_dumm.date.max()]
            test_dumm =imp_fert_dumm[imp_fert_dumm.date==imp_fert_dumm.date.max()]
    
            # Identifica X e y
            X_train_r=train_dumm.drop(columns=['KG_LIQUIDO','oc'])
            y_train_r=train_dumm.KG_LIQUIDO
            
            X_test_r =test_dumm.drop(columns=['KG_LIQUIDO','oc'])
            y_test_r =test_dumm.KG_LIQUIDO
            
            # Fit regressor
            RFR.fit(X_train_r,y_train_r)
            
            # Predict classifier
            test_pred_r=X_test_r.assign(kg_pred=RFR.predict(X_test_r)).assign(KG_LIQUIDO=y_test_r)

            r=pd.concat([r,test_pred_r])
        
        
    
    f_p=time.time()
    print(f"Date {date.date()} : Parcial:{round((f_p-i_p)/60,3)} minutos.")

Date 1997-03-01 : Parcial:0.0 minutos.
Date 1997-04-01 : Parcial:0.0 minutos.
Date 1997-05-01 : Parcial:0.0 minutos.
Date 1997-06-01 : Parcial:0.0 minutos.
Date 1997-07-01 : Parcial:0.0 minutos.
Date 1997-08-01 : Parcial:0.0 minutos.
Date 1997-09-01 : Parcial:0.0 minutos.
Date 1997-10-01 : Parcial:0.0 minutos.
Date 1997-11-01 : Parcial:0.0 minutos.
Date 1997-12-01 : Parcial:0.0 minutos.
Date 1998-01-01 : Parcial:0.001 minutos.
Date 1998-02-01 : Parcial:0.0 minutos.
Date 1998-03-01 : Parcial:0.0 minutos.
Date 1998-04-01 : Parcial:0.0 minutos.
Date 1998-05-01 : Parcial:0.0 minutos.
Date 1998-06-01 : Parcial:0.0 minutos.
Date 1998-07-01 : Parcial:0.0 minutos.
Date 1998-08-01 : Parcial:0.0 minutos.
Date 1998-09-01 : Parcial:0.0 minutos.
Date 1998-10-01 : Parcial:0.0 minutos.
Date 1998-11-01 : Parcial:0.0 minutos.
Date 1998-12-01 : Parcial:0.0 minutos.
Date 1999-01-01 : Parcial:0.0 minutos.
Date 1999-02-01 : Parcial:0.0 minutos.
Date 1999-03-01 : Parcial:0.0 minutos.
Date 1999-04-01 : Parcial:0.0 minutos.
Date 1999-05-01 : Parcial:0.0 minutos.
Date 1999-06-01 : Parcial:0.0 minutos.
Date 1999-07-01 : Parcial:0.0 minutos.
Date 1999-08-01 : Parcial:0.0 minutos.
Date 1999-09-01 : Parcial:0.0 minutos.
Date 1999-10-01 : Parcial:0.0 minutos.
Date 1999-11-01 : Parcial:0.0 minutos.
Date 1999-12-01 : Parcial:0.0 minutos.
Date 2000-01-01 : Parcial:0.0 minutos.
Date 2000-02-01 : Parcial:0.0 minutos.
Date 2000-03-01 : Parcial:0.0 minutos.
Date 2000-04-01 : Parcial:0.0 minutos.
Date 2000-05-01 : Parcial:0.0 minutos.
Date 2000-06-01 : Parcial:0.0 minutos.
Date 2000-07-01 : Parcial:0.0 minutos.
Date 2000-08-01 : Parcial:0.0 minutos.
Date 2000-09-01 : Parcial:0.0 minutos.
Date 2000-10-01 : Parcial:0.0 minutos.
Date 2000-11-01 : Parcial:0.0 minutos.
Date 2000-12-01 : Parcial:0.0 minutos.
Date 2001-01-01 : Parcial:0.0 minutos.
Date 2001-02-01 : Parcial:0.0 minutos.
Date 2001-03-01 : Parcial:0.0 minutos.
Date 2001-04-01 : Parcial:0.0 minutos.
Date 2001-05-01 : Parcial:0.0 minutos.
Date 2001-06-01 : Parcial:0.0 minutos.
Date 2001-07-01 : Parcial:0.0 minutos.
Date 2001-08-01 : Parcial:0.0 minutos.
Date 2001-09-01 : Parcial:0.0 minutos.
Date 2001-10-01 : Parcial:0.0 minutos.
Date 2001-11-01 : Parcial:0.0 minutos.
Date 2001-12-01 : Parcial:0.0 minutos.
Date 2002-01-01 : Parcial:0.0 minutos.
Date 2002-02-01 : Parcial:0.0 minutos.
Date 2002-03-01 : Parcial:0.0 minutos.
Date 2002-04-01 : Parcial:0.0 minutos.
Date 2002-05-01 : Parcial:0.0 minutos.
Date 2002-06-01 : Parcial:0.0 minutos.
Date 2002-07-01 : Parcial:0.0 minutos.
Date 2002-08-01 : Parcial:0.0 minutos.
Date 2002-09-01 : Parcial:0.0 minutos.
Date 2002-10-01 : Parcial:0.0 minutos.
Date 2002-11-01 : Parcial:0.0 minutos.
Date 2002-12-01 : Parcial:0.0 minutos.
Date 2003-01-01 : Parcial:0.0 minutos.
Date 2003-02-01 : Parcial:0.0 minutos.
Date 2003-03-01 : Parcial:0.0 minutos.
Date 2003-04-01 : Parcial:0.0 minutos.
Date 2003-05-01 : Parcial:0.0 minutos.
Date 2003-06-01 : Parcial:0.0 minutos.
Date 2003-07-01 : Parcial:0.0 minutos.
Date 2003-08-01 : Parcial:0.0 minutos.
Date 2003-09-01 : Parcial:0.0 minutos.
Date 2003-10-01 : Parcial:0.0 minutos.
Date 2003-11-01 : Parcial:0.0 minutos.
Date 2003-12-01 : Parcial:0.0 minutos.
Date 2004-01-01 : Parcial:0.0 minutos.
Date 2004-02-01 : Parcial:0.0 minutos.
Date 2004-03-01 : Parcial:0.0 minutos.
Date 2004-04-01 : Parcial:0.0 minutos.
Date 2004-05-01 : Parcial:0.0 minutos.
Date 2004-06-01 : Parcial:0.0 minutos.
Date 2004-07-01 : Parcial:0.0 minutos.
Date 2004-08-01 : Parcial:0.0 minutos.
Date 2004-09-01 : Parcial:0.0 minutos.
Date 2004-10-01 : Parcial:0.0 minutos.
Date 2004-11-01 : Parcial:0.0 minutos.
Date 2004-12-01 : Parcial:0.0 minutos.
Date 2005-01-01 : Parcial:0.0 minutos.
Date 2005-02-01 : Parcial:0.0 minutos.
Date 2005-03-01 : Parcial:0.0 minutos.
Date 2005-04-01 : Parcial:0.0 minutos.
Date 2005-05-01 : Parcial:0.0 minutos.
Date 2005-06-01 : Parcial:0.0 minutos.
Date 2005-07-01 : Parcial:0.0 minutos.
Date 2005-08-01 : Parcial:0.0 minutos.
Date 2005-09-01 : Parcial:0.0 minutos.
Date 2005-10-01 : Parcial:0.0 minutos.
Date 2005-11-01 : Parcial:0.0 minutos.
Date 2005-12-01 : Parcial:0.0 minutos.
Date 2006-01-01 : Parcial:0.0 minutos.
Date 2006-02-01 : Parcial:0.0 minutos.
Date 2006-03-01 : Parcial:0.0 minutos.
Date 2006-04-01 : Parcial:0.0 minutos.
Date 2006-05-01 : Parcial:0.0 minutos.
Date 2006-06-01 : Parcial:0.0 minutos.
Date 2006-07-01 : Parcial:0.0 minutos.
Date 2006-08-01 : Parcial:0.0 minutos.
Date 2006-09-01 : Parcial:0.0 minutos.
Date 2006-10-01 : Parcial:0.0 minutos.
Date 2006-11-01 : Parcial:0.0 minutos.
Date 2006-12-01 : Parcial:0.0 minutos.
Date 2007-01-01 : Parcial:0.0 minutos.
Date 2007-02-01 : Parcial:0.0 minutos.
Date 2007-03-01 : Parcial:0.005 minutos.
Date 2007-04-01 : Parcial:0.005 minutos.
Date 2007-05-01 : Parcial:0.007 minutos.
Date 2007-06-01 : Parcial:0.009 minutos.
Date 2007-07-01 : Parcial:0.009 minutos.
Date 2007-08-01 : Parcial:0.006 minutos.
Date 2007-09-01 : Parcial:0.014 minutos.
Date 2007-10-01 : Parcial:0.008 minutos.
Date 2007-11-01 : Parcial:0.004 minutos.
Date 2007-12-01 : Parcial:0.006 minutos.
Date 2008-01-01 : Parcial:0.004 minutos.
Date 2008-02-01 : Parcial:0.005 minutos.
Date 2008-03-01 : Parcial:0.006 minutos.
Date 2008-04-01 : Parcial:0.004 minutos.
Date 2008-05-01 : Parcial:0.005 minutos.
Date 2008-06-01 : Parcial:0.007 minutos.
Date 2008-07-01 : Parcial:0.008 minutos.
Date 2008-08-01 : Parcial:0.009 minutos.
Date 2008-09-01 : Parcial:0.008 minutos.
Date 2008-10-01 : Parcial:0.011 minutos.
Date 2008-11-01 : Parcial:0.006 minutos.
Date 2008-12-01 : Parcial:0.006 minutos.
Date 2009-01-01 : Parcial:0.01 minutos.
Date 2009-02-01 : Parcial:0.01 minutos.
Date 2009-03-01 : Parcial:0.014 minutos.
Date 2009-04-01 : Parcial:0.008 minutos.
Date 2009-05-01 : Parcial:0.005 minutos.
Date 2009-06-01 : Parcial:0.007 minutos.
Date 2009-07-01 : Parcial:0.006 minutos.
Date 2009-08-01 : Parcial:0.008 minutos.
Date 2009-09-01 : Parcial:0.006 minutos.
Date 2009-10-01 : Parcial:0.009 minutos.
Date 2009-11-01 : Parcial:0.008 minutos.
Date 2009-12-01 : Parcial:0.009 minutos.
Date 2010-01-01 : Parcial:0.006 minutos.
Date 2010-02-01 : Parcial:0.008 minutos.
Date 2010-03-01 : Parcial:0.006 minutos.
Date 2010-04-01 : Parcial:0.006 minutos.
Date 2010-05-01 : Parcial:0.006 minutos.
Date 2010-06-01 : Parcial:0.008 minutos.
Date 2010-07-01 : Parcial:0.006 minutos.
Date 2010-08-01 : Parcial:0.008 minutos.
Date 2010-09-01 : Parcial:0.006 minutos.
Date 2010-10-01 : Parcial:0.007 minutos.
Date 2010-11-01 : Parcial:0.007 minutos.
Date 2010-12-01 : Parcial:0.007 minutos.
Date 2011-01-01 : Parcial:0.01 minutos.
Date 2011-02-01 : Parcial:0.008 minutos.
Date 2011-03-01 : Parcial:0.007 minutos.
Date 2011-04-01 : Parcial:0.007 minutos.
Date 2011-05-01 : Parcial:0.01 minutos.
Date 2011-06-01 : Parcial:0.009 minutos.
Date 2011-07-01 : Parcial:0.007 minutos.
Date 2011-08-01 : Parcial:0.009 minutos.
Date 2011-09-01 : Parcial:0.006 minutos.
Date 2011-10-01 : Parcial:0.007 minutos.
Date 2011-11-01 : Parcial:0.01 minutos.
Date 2011-12-01 : Parcial:0.007 minutos.
Date 2012-01-01 : Parcial:0.009 minutos.
Date 2012-02-01 : Parcial:0.007 minutos.
Date 2012-03-01 : Parcial:0.009 minutos.
Date 2012-04-01 : Parcial:0.007 minutos.
Date 2012-05-01 : Parcial:0.006 minutos.
Date 2012-06-01 : Parcial:0.008 minutos.
Date 2012-07-01 : Parcial:0.008 minutos.
Date 2012-08-01 : Parcial:0.007 minutos.
Date 2012-09-01 : Parcial:0.013 minutos.
Date 2012-10-01 : Parcial:0.01 minutos.
Date 2012-11-01 : Parcial:0.009 minutos.
Date 2012-12-01 : Parcial:0.008 minutos.
Date 2013-01-01 : Parcial:0.009 minutos.
Date 2013-02-01 : Parcial:0.009 minutos.
Date 2013-03-01 : Parcial:0.011 minutos.
Date 2013-04-01 : Parcial:0.007 minutos.
Date 2013-05-01 : Parcial:0.011 minutos.
Date 2013-06-01 : Parcial:0.007 minutos.
Date 2013-07-01 : Parcial:0.009 minutos.
Date 2013-08-01 : Parcial:0.007 minutos.
Date 2013-09-01 : Parcial:0.008 minutos.
Date 2013-10-01 : Parcial:0.009 minutos.
Date 2013-11-01 : Parcial:0.007 minutos.
Date 2013-12-01 : Parcial:0.009 minutos.
Date 2014-01-01 : Parcial:0.009 minutos.
Date 2014-02-01 : Parcial:0.008 minutos.
Date 2014-03-01 : Parcial:0.01 minutos.
Date 2014-04-01 : Parcial:0.007 minutos.
Date 2014-05-01 : Parcial:0.008 minutos.
Date 2014-06-01 : Parcial:0.011 minutos.
Date 2014-07-01 : Parcial:0.008 minutos.
Date 2014-08-01 : Parcial:0.009 minutos.
Date 2014-09-01 : Parcial:0.01 minutos.
Date 2014-10-01 : Parcial:0.012 minutos.
Date 2014-11-01 : Parcial:0.011 minutos.
Date 2014-12-01 : Parcial:0.008 minutos.
Date 2015-01-01 : Parcial:0.009 minutos.
Date 2015-02-01 : Parcial:0.009 minutos.
Date 2015-03-01 : Parcial:0.009 minutos.
Date 2015-04-01 : Parcial:0.009 minutos.
Date 2015-05-01 : Parcial:0.011 minutos.
Date 2015-06-01 : Parcial:0.011 minutos.
Date 2015-07-01 : Parcial:0.013 minutos.
Date 2015-08-01 : Parcial:0.009 minutos.
Date 2015-09-01 : Parcial:0.009 minutos.
Date 2015-10-01 : Parcial:0.009 minutos.
Date 2015-11-01 : Parcial:0.008 minutos.
Date 2015-12-01 : Parcial:0.009 minutos.
Date 2016-01-01 : Parcial:0.01 minutos.
Date 2016-02-01 : Parcial:0.013 minutos.
Date 2016-03-01 : Parcial:0.012 minutos.
Date 2016-04-01 : Parcial:0.009 minutos.
Date 2016-05-01 : Parcial:0.013 minutos.
Date 2016-06-01 : Parcial:0.011 minutos.
Date 2016-07-01 : Parcial:0.01 minutos.
Date 2016-08-01 : Parcial:0.009 minutos.
Date 2016-09-01 : Parcial:0.011 minutos.
Date 2016-10-01 : Parcial:0.012 minutos.
Date 2016-11-01 : Parcial:0.009 minutos.
Date 2016-12-01 : Parcial:0.011 minutos.
Date 2017-01-01 : Parcial:0.011 minutos.
Date 2017-02-01 : Parcial:0.011 minutos.
Date 2017-03-01 : Parcial:0.008 minutos.
Date 2017-04-01 : Parcial:0.009 minutos.
Date 2017-05-01 : Parcial:0.011 minutos.
Date 2017-06-01 : Parcial:0.009 minutos.
Date 2017-07-01 : Parcial:0.012 minutos.
Date 2017-08-01 : Parcial:0.01 minutos.
Date 2017-09-01 : Parcial:0.009 minutos.
Date 2017-10-01 : Parcial:0.01 minutos.
Date 2017-11-01 : Parcial:0.01 minutos.
Date 2017-12-01 : Parcial:0.009 minutos.
Date 2018-01-01 : Parcial:0.01 minutos.
Date 2018-02-01 : Parcial:0.019 minutos.
Date 2018-03-01 : Parcial:0.026 minutos.
Date 2018-04-01 : Parcial:0.015 minutos.
Date 2018-05-01 : Parcial:0.013 minutos.
Date 2018-06-01 : Parcial:0.013 minutos.
Date 2018-07-01 : Parcial:0.013 minutos.
Date 2018-08-01 : Parcial:0.013 minutos.
Date 2018-09-01 : Parcial:0.013 minutos.
Date 2018-10-01 : Parcial:0.014 minutos.
Date 2018-11-01 : Parcial:0.013 minutos.
Date 2018-12-01 : Parcial:0.014 minutos.
Date 2019-01-01 : Parcial:0.015 minutos.
Date 2019-02-01 : Parcial:0.017 minutos.
Date 2019-03-01 : Parcial:0.016 minutos.
Date 2019-04-01 : Parcial:0.018 minutos.
Date 2019-05-01 : Parcial:0.016 minutos.
Date 2019-06-01 : Parcial:0.017 minutos.
Date 2019-07-01 : Parcial:0.017 minutos.
Date 2019-08-01 : Parcial:0.016 minutos.
Date 2019-09-01 : Parcial:0.016 minutos.
Date 2019-10-01 : Parcial:0.014 minutos.
Date 2019-11-01 : Parcial:0.014 minutos.
Date 2019-12-01 : Parcial:0.014 minutos.
Date 2020-01-01 : Parcial:0.016 minutos.
Date 2020-02-01 : Parcial:0.016 minutos.
Date 2020-03-01 : Parcial:0.016 minutos.
Date 2020-04-01 : Parcial:0.017 minutos.
Date 2020-05-01 : Parcial:0.015 minutos.
Date 2020-06-01 : Parcial:0.017 minutos.
Date 2020-07-01 : Parcial:0.017 minutos.
Date 2020-08-01 : Parcial:0.016 minutos.
Date 2020-09-01 : Parcial:0.015 minutos.
Date 2020-10-01 : Parcial:0.016 minutos.
Date 2020-11-01 : Parcial:0.017 minutos.
Date 2020-12-01 : Parcial:0.017 minutos.
Date 2021-01-01 : Parcial:0.016 minutos.
Date 2021-02-01 : Parcial:0.018 minutos.
Date 2021-03-01 : Parcial:0.016 minutos.
Date 2021-04-01 : Parcial:0.019 minutos.
Date 2021-05-01 : Parcial:0.024 minutos.
Date 2021-06-01 : Parcial:0.019 minutos.
Date 2021-07-01 : Parcial:0.016 minutos.
Date 2021-08-01 : Parcial:0.016 minutos.
Date 2021-09-01 : Parcial:0.017 minutos.
Date 2021-10-01 : Parcial:0.017 minutos.
Date 2021-11-01 : Parcial:0.017 minutos.
Date 2021-12-01 : Parcial:0.017 minutos.
Date 2022-01-01 : Parcial:0.016 minutos.
Date 2022-02-01 : Parcial:0.017 minutos.
Date 2022-03-01 : Parcial:0.019 minutos.
Date 2022-04-01 : Parcial:0.017 minutos.
Date 2022-05-01 : Parcial:0.017 minutos.
Date 2022-06-01 : Parcial:0.018 minutos.
Date 2022-07-01 : Parcial:0.017 minutos.
Date 2022-08-01 : Parcial:0.018 minutos.
Date 2022-09-01 : Parcial:0.018 minutos.
Date 2022-10-01 : Parcial:0.018 minutos.
Date 2022-11-01 : Parcial:0.018 minutos.
Date 2022-12-01 : Parcial:0.018 minutos.
Date 2023-01-01 : Parcial:0.018 minutos.
Date 2023-02-01 : Parcial:0.021 minutos.
Date 2023-03-01 : Parcial:0.018 minutos.
Date 2023-04-01 : Parcial:0.019 minutos.
Date 2023-05-01 : Parcial:0.02 minutos.
Date 2023-06-01 : Parcial:0.02 minutos.
Date 2023-07-01 : Parcial:0.02 minutos.
Date 2023-08-01 : Parcial:0.02 minutos.
Date 2023-09-01 : Parcial:0.019 minutos.
Date 2023-10-01 : Parcial:0.018 minutos.
Date 2023-11-01 : Parcial:0.018 minutos.
Date 2023-12-01 : Parcial:0.019 minutos.
Date 2024-01-01 : Parcial:0.019 minutos.
Date 2024-02-01 : Parcial:0.02 minutos.
Date 2024-03-01 : Parcial:0.02 minutos.
Date 2024-04-01 : Parcial:0.019 minutos.

In [13]:
f=time.time()
d=f-i
print(f"Duração de {round(d/60)} minutos.")

Duração de 2 minutos.

In [14]:
def f_dumm(df_dumm):
    a=pd.from_dummies(df_dumm.select_dtypes(include='bool'),sep='~')
    b=df_dumm.select_dtypes(exclude='bool')
    c=pd.concat([a,b],axis=1)
    return c

In [15]:
q=f_dumm(q)

In [16]:
r=f_dumm(r)

In [17]:
q

      CO_ANO CO_MES     nick CO_PAIS  CO_URF                 date  oc_pred  oc
5368    2007      3    MAP_k     160  317900  1172707200000000000        0   0
5369    2007      3    MAP_k     160  417900  1172707200000000000        0   0
5370    2007      3    MAP_k     160  517800  1172707200000000000        0   0
5371    2007      3    MAP_k     160  717600  1172707200000000000        0   0
5372    2007      3    MAP_k     160  717800  1172707200000000000        0   0
...      ...    ...      ...     ...     ...                  ...      ...  ..
14427   2024      4  UREIA_k     676  517800  1711929600000000000        0   1
14428   2024      4  UREIA_k     676  817800  1711929600000000000        0   0
14429   2024      4  UREIA_k     676  917800  1711929600000000000        0   0
14430   2024      4  UREIA_k     676  927700  1711929600000000000        0   0
14431   2024      4  UREIA_k     999  517800  1711929600000000000        1   1

[9064 rows x 8 columns]

In [18]:
q.merge(r,how='outer').to_csv('~/git/BD/temp/q-menos_UF.csv',index=False)