In [1]:
import time
ini=time.time()

In [2]:
year_testing=10

In [3]:
import numpy as np
import pandas as pd
from pandas.tseries.offsets import DateOffset
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
comex_0=pd.read_csv('/home/andre301267/git/Pricing-Fertilizer/DB/temp/imp_fert_ncm_quanti.csv')

In [4]:
prdt_lonely=['MOP']
uf_lonely=['BA']
prdt_conj=['MOP','MAP','UREIA','SAM']
uf_conj=['BA','TO','GO']
lonely=[prdt_lonely,uf_lonely]
conj=[prdt_conj,uf_conj]
hip_list = [lonely,conj]

In [5]:
for f in hip_list:

    # Filtra produto e UF
    comex_df=comex_0[(comex_0.Product.isin(f[0]))&(comex_0.UF.isin(f[1]))]
    
    # filtra km deixando passar o maior km de cada produto
    filtra_km=comex_df[['Product','km']].drop_duplicates().sort_values(by=['Product','km'],ascending=False)\
        .drop_duplicates(subset='Product')
    comex_df=comex_df.merge(filtra_km)
    
    # Save real begins and ends
    comex_df['date']=pd.to_datetime(comex_df.year.astype(str)+'-'+comex_df.month.astype(str)+'-01')
    date_min=comex_df.date.min()
    date_max=comex_df.date.max()
    
    # Calendar full
    years=pd.DataFrame({'year':np.arange(comex_df.year.min(),
                                         comex_df.year.max()+1)}).assign(key=0)
    months=pd.DataFrame({'month':np.arange(1,13)}).assign(key=0)
    calendar=years.merge(months,on='key')
    calendar_full=comex_df[['Product','UF']].drop_duplicates().assign(key=0).merge(calendar,on='key').drop('key',axis=1)
    
    # Merge calendar full
    comex_df=comex_df.merge(calendar_full)
    
    # Saprse Matrix
    comex_df[['month','Product','UF']]=comex_df[['month', 'Product','UF']].astype('category')
    comex_df=comex_df.groupby(by=['year','month','Product','UF'],observed=False).kg.sum().reset_index()
    
    # Prune
    comex_df['date']=pd.to_datetime(comex_df.year.astype(str)+'-'+comex_df.month.astype(str)+'-01')
    comex_df=comex_df[(comex_df.date>=date_min)&(comex_df.date<=date_max)]
    
    # Dummies
    comex_df=pd.get_dummies(comex_df,prefix_sep='~')

    # Classify
    
    comex_df=comex_df.assign(oc=0)
    comex_df.loc[comex_df.kg>0,'oc']=1
    
    comex_df_t=comex_df.copy()
    for r in range(1,year_testing+1):
        train=comex_df_t[comex_df_t.date<comex_df_t.date.max()]
        test=comex_df_t[comex_df_t.date==comex_df_t.date.max()]
        X_train=train.drop(['kg','oc','date'],axis=1)
        y_train=train.oc
        X_test=test.drop(['kg','oc','date'],axis=1)
        y_test=test.oc
        from sklearn.ensemble import RandomForestClassifier as rfc
        model=rfc()
        model.fit(X_train,y_train)
        y_pred=model.predict(X_test)
        test['y_pred']=y_pred
        if r==1:
            results=test
        else:
            results=pd.concat([results,test])
        
        comex_df_t=comex_df_t[comex_df_t.date<=comex_df_t.date.max()-DateOffset(years=1)]
    
    # Regression
    
    comex_df=results.merge(comex_df,how='outer')
    
    comex_df=comex_df[(comex_df.oc==1)&(comex_df.y_pred.isin([1,np.nan]))].drop(columns='y_pred')
    
    comex_df_t=comex_df.copy()
    features_df=pd.DataFrame()
    for r in range(1,year_testing+1):
        train=comex_df_t[comex_df_t.date<comex_df_t.date.max()]
        test=comex_df_t[comex_df_t.date==comex_df_t.date.max()]
        X_train=train.drop(['kg','oc','date'],axis=1)
        y_train=train.kg
        X_test=test.drop(['kg','oc','date'],axis=1)
        y_test=test.kg
        from sklearn.ensemble import RandomForestRegressor as rfr
        model=rfr(max_depth=10,max_features=5)
        model.fit(X_train,y_train)
        t=pd.DataFrame({'names':model.feature_names_in_,'importances':model.feature_importances_})
        features_df=pd.concat([features_df,t])
        y_pred=model.predict(X_test)
        test['y_pred']=y_pred
        if r==1:
            results=test
        else:
            results=pd.concat([results,test])
        
        comex_df_t=comex_df_t[comex_df_t.date<=comex_df_t.date.max()-DateOffset(years=1)]
    
    print('\n',f)
    display(features_df.groupby('names').importances.mean().reset_index().sort_values(by='importances',ascending=False))

    o=results[results.columns[~results.columns.str.contains('~')]]
    
    prdt=pd.from_dummies(results[results.columns[results.columns.str.contains('Pro')]],sep='~')
    
    month=pd.from_dummies(results[results.columns[results.columns.str.contains('month')]],sep='~')
    
    uf=pd.from_dummies(results[results.columns[results.columns.str.contains('UF')]],sep='~')
    
    results=pd.concat([o,prdt,month,uf],axis=1)
    
    mes=results.month.unique()[0]
    
    results[(results.Product=='MOP')&(results.month==mes)&(results.UF=='BA')]
    
    from sklearn.metrics import root_mean_squared_error as rse
    results['rse']=rse(results.kg,results.y_pred)
    
    print(f"\nPara {f} - rse={int(results.rse.unique()/10**6)}")

 [['MOP'], ['BA']]

          names  importances
14         year     0.675477
13      month~9     0.036880
11      month~7     0.036534
4      month~11     0.035403
12      month~8     0.030379
8       month~4     0.027374
2       month~1     0.026994
5      month~12     0.026484
3      month~10     0.025851
7       month~3     0.023646
10      month~6     0.021682
6       month~2     0.018188
9       month~5     0.015107
0   Product~MOP     0.000000
1         UF~BA     0.000000

Para [['MOP'], ['BA']] - rse=18

 [['MOP', 'MAP', 'UREIA', 'SAM'], ['BA', 'TO', 'GO']]

            names  importances
19           year     0.329637
1     Product~MOP     0.237713
2     Product~SAM     0.092535
6           UF~TO     0.052852
5           UF~GO     0.051702
4           UF~BA     0.032059
3   Product~UREIA     0.030828
0     Product~MAP     0.029554
11        month~2     0.014699
18        month~9     0.013527
7         month~1     0.013101
17        month~8     0.013094
14        month~5     0.013071
15        month~6     0.012928
16        month~7     0.012665
8        month~10     0.011449
10       month~12     0.011393
9        month~11     0.010715
13        month~4     0.009228
12        month~3     0.007250

Para [['MOP', 'MAP', 'UREIA', 'SAM'], ['BA', 'TO', 'GO']] - rse=18

In [6]:
end=time.time()
print(f"Duração: {round((end-ini)/60,1)} minutos.")

Duração: 0.2 minutos.