# Visualiza primeiras linhas do interno

In [8]:
import zipfile
import pandas as pd
import os

# Número de linhas a serem lidas
num_linhas = 5  # Defina o número de linhas que deseja exibir

def vslz_primeiras_linhas(local_filename,internal_zipfile):
    # Abrir o arquivo ZIP em modo leitura
    with zipfile.ZipFile(local_filename, 'r') as zip_ref:
        # Extrair o arquivo CSV temporariamente
        with zip_ref.open(internal_zipfile) as csv_file:
            # Ler as primeiras linhas do arquivo CSV
            df = pd.read_csv(csv_file, nrows=num_linhas, encoding='Latin-1',sep=';')
            # Exibir as primeiras linhas em formato de tabela
            display(df)
print('** Função vslz_primeiras_linhas(local_filename,internal_zipfile) disponível**')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB,VL_FRETE,VL_SEGURO
0,1997,9,29251990,10,87,SP,1,817800,200,200,4888,180,24
1,1997,8,85049010,10,399,SP,4,817600,4891,84,30116,409,93
2,1997,8,54023300,10,63,SP,7,1010900,143834,143834,402427,10121,266
3,1997,3,38121000,10,249,SP,1,817800,9434,9172,61190,3011,163
4,1997,10,73209000,10,399,SP,4,817600,222510,49,3638,456,18