In [1]:
import time
inicio=time.time()

In [2]:
import numpy as np
import pandas as pd

In [3]:
imp_fert=pd.read_csv('~/git/BD/temp/imp_fert_quanti_g_ncm_uf.csv').sort_values(by=['CO_ANO','CO_MES']).reset_index(drop=True)

In [4]:
imp_fert=imp_fert.loc[:,:'KG_LIQUIDO']

filt_ncm=imp_fert.groupby('CO_NCM').KG_LIQUIDO.sum().sort_values(ascending=False).head(2).reset_index().CO_NCM.values[:1]
imp_fert=imp_fert[imp_fert.CO_NCM.isin(filt_ncm)]

filt_uf=imp_fert.groupby('SG_UF_NCM').KG_LIQUIDO.sum().sort_values(ascending=False).head(2).reset_index().SG_UF_NCM.values[:1]
imp_fert=imp_fert[imp_fert.SG_UF_NCM.isin(filt_uf)]

In [8]:
imp_fert.to_csv('~/git/BD/temp/temp.csv',index=False)

In [10]:
%run '~/git/multi.ipynb'

In [11]:
imp_fert=pd.read_csv('~/git/BD/temp/temp_out.csv')

In [12]:
imp_fert

,date,CO_ANO,CO_MES,CO_NCM,SG_UF_NCM,KG_LIQUIDO,31021010-hi~0,31021010-hi~BA,31021010-hi~GO,31021010-hi~MA,...,31055900-hi~BA,31055900-hi~GO,31055900-hi~MA,31055900-hi~MG,31055900-hi~MS,31055900-hi~MT,31055900-hi~PR,31055900-hi~RS,31055900-hi~SC,31055900-hi~SP
0,1997-02-01,1997,2,31021010-hi,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1997-02-01,1997,2,31021010-hi,BA,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1997-02-01,1997,2,31021010-hi,GO,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1997-02-01,1997,2,31021010-hi,MA,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1997-02-01,1997,2,31021010-hi,MG,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25790,2024-12-01,2024,12,31055900-hi,MT,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25791,2024-12-01,2024,12,31055900-hi,PR,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25792,2024-12-01,2024,12,31055900-hi,RS,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25793,2024-12-01,2024,12,31055900-hi,SC,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25794,2024-12-01,2024,12,31055900-hi,SP,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
%run '~/git/prev_score_ncm_uf.py'

Disponível função prev_score(ano_mes_ncm_uf)

In [14]:
q=prev_score(imp_fert)

/home/andre301267/git/prev_score_ncm_uf.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ano_mes_ncm_uf[cat_cols]=ano_mes_ncm_uf[cat_cols].astype('category')

In [15]:
q.to_csv('~/git/BD/temp/prev_score_quanti_multi1.csv',index=False)

In [16]:
fim=time.time()
d=fim-inicio
print(f'Duração:{round(d/60)} minutos.')

Duração:16 minutos.

In [17]:
q[['accuracy','precision','recall','r2']].mean()

accuracy      0.614965
precision     0.721405
recall        0.685311
r2          -33.999018
dtype: float64

In [18]:
round(q.groupby('CO_NCM')[q.columns[3:]].mean(),1)

/tmp/ipykernel_5620/2220920743.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  round(q.groupby('CO_NCM')[q.columns[3:]].mean(),1)

             accuracy  precision  recall     r2
CO_NCM
31021010-hi       0.6        0.8     0.7   -2.9
31022100-hi       0.6        0.8     0.6   -3.3
31023000-hi       0.5        0.4     0.5 -253.6
31042090-hi       0.6        0.9     0.6   -0.9
31052000-hi       0.7        0.6     0.9  -22.4
31054000-hi       0.7        0.9     0.7   -3.6
31055900-hi       0.6        0.7     0.8  -11.1

In [19]:
round(q.groupby('SG_UF_NCM')[q.columns[3:]].mean(),1)

/tmp/ipykernel_5620/92138848.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  round(q.groupby('SG_UF_NCM')[q.columns[3:]].mean(),1)

           accuracy  precision  recall     r2
SG_UF_NCM
0               0.6        0.7     0.7  -63.9
BA              0.6        0.6     0.6  -27.3
GO              0.6        0.8     0.7   -4.7
MA              0.6        0.5     0.7   -3.4
MG              0.7        0.9     0.7   -2.0
MS              0.6        0.7     0.7  -44.4
MT              0.6        0.7     0.7 -199.1
PR              0.7        0.9     0.7   -1.3
RS              0.6        0.7     0.7   -2.8
SC              0.5        0.5     0.6  -13.4
SP              0.6        0.9     0.7   -3.5

In [20]:
round(q.groupby('CO_MES')[q.columns[3:]].mean(),1)

/tmp/ipykernel_5620/3954593838.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  round(q.groupby('CO_MES')[q.columns[3:]].mean(),1)

        accuracy  precision  recall    r2
CO_MES
1            0.6        0.7     0.7 -34.0
2            0.6        0.7     0.7 -34.0
3            0.6        0.7     0.7 -34.0
4            0.6        0.7     0.7 -34.0
5            0.6        0.7     0.7 -34.0
6            0.6        0.7     0.7 -34.0
7            0.6        0.7     0.7 -34.0
8            0.6        0.7     0.7 -34.0
9            0.6        0.7     0.7 -34.0
10           0.6        0.7     0.7 -34.0
11           0.6        0.7     0.7 -34.0
12           0.6        0.7     0.7 -34.0